"""Investment themes: the big structural stories that drove multi-fold moves in Indian stocks.

Each theme has: a one-line thesis, a start year (news history is collected from then),
a timeline of milestones, the NSE symbols that ride it, and search phrases for news.
Symbols that are not in the dashboard's stock list are skipped automatically, so a
renamed or delisted symbol does no harm.

To add or change themes without touching code, put a file called themes.json in the
repository root with the same fields (a list of themes). It replaces this list.
The timelines are short summaries for orientation; check details before relying on them.
"""

THEMES = [
    {"id": "china1chem", "name": "China+1: specialty chemicals",
     "thesis": "Global buyers moved chemical supply away from China after its environmental shutdowns and COVID disruptions; Indian specialty chemical makers won long contracts and expanded capacity.",
     "start": 2017,
     "timeline": [["2017", "China's environmental inspections shut many chemical plants; global buyers look for a second source."],
                  ["2020", "COVID disrupts Chinese supply; 'China+1' sourcing becomes a board-level priority for global companies."],
                  ["2020-21", "Indian specialty chemical stocks re-rate sharply; several new listings (e.g. Anupam Rasayan, Clean Science)."],
                  ["2022-23", "Global destocking and cheap Chinese exports hit prices and margins; most of the group corrects hard."],
                  ["2024-25", "Destocking eases; fluorochemicals and agrochemical intermediates lead a partial recovery."]],
     "stocks": ["SRF", "PIIND", "DEEPAKNTR", "AARTIIND", "NAVINFLUOR", "ATUL", "CLEAN", "FINEORG", "GALAXYSURF", "VINATIORGA",
                "ALKYLAMINE", "BALAMINES", "FLUOROCHEM", "ANURAS", "NOCIL", "SUDARSCHEM", "LXCHEM", "ROSSARI", "TATACHEM", "CHEMPLASTS", "JUBLINGREA"],
     "q": ["China plus one India chemical", "specialty chemicals India exports capacity"]},
    {"id": "semis", "name": "Semiconductors and electronics manufacturing",
     "thesis": "The 2021 chip shortage and the India Semiconductor Mission (with PLI schemes for phones and components) are building a domestic electronics and chip-packaging industry.",
     "start": 2021,
     "timeline": [["2021", "Global chip shortage halts car and electronics production worldwide."],
                  ["Dec 2021", "India approves the India Semiconductor Mission (about ₹76,000 crore of incentives)."],
                  ["Jun 2023", "Micron announces a chip assembly and test plant at Sanand, Gujarat."],
                  ["Feb 2024", "Cabinet approves a Tata fab (with PSMC) at Dholera and packaging units by Tata and CG Power–Renesas."],
                  ["2024-25", "Further packaging units approved (e.g. Kaynes); first India-made chips from pilot lines shown in 2025."]],
     "stocks": ["DIXON", "KAYNES", "SYRMA", "AMBER", "PGEL", "AVALON", "CGPOWER", "MOSCHIP", "SPEL", "CENTUM", "TATAELXSI", "DATAPATTNS", "SAHASRA", "ELIN"],
     "q": ["India semiconductor mission", "India electronics manufacturing PLI"]},
    {"id": "defence", "name": "Defence: make in India and exports",
     "thesis": "Import bans on hundreds of defence items, rising budgets and record exports shift orders to Indian manufacturers.",
     "start": 2020,
     "timeline": [["May 2020", "Atmanirbhar Bharat push; defence FDI limit raised to 74% under the automatic route."],
                  ["Aug 2020", "First positive indigenisation list bans imports of 101 items; more lists follow."],
                  ["2023-24", "Defence exports reach a record; order books of PSU and private defence makers swell."],
                  ["May 2025", "Operation Sindoor; renewed focus on air defence, missiles and drones lifts the group."]],
     "stocks": ["HAL", "BEL", "BDL", "MAZDOCK", "COCHINSHIP", "GRSE", "BEML", "DATAPATTNS", "PARAS", "ASTRAMICRO", "SOLARINDS", "MTARTECH",
                "ZENTEC", "BHARATFORG", "HBLENGINE", "MIDHANI", "DCXINDIA", "APOLLO", "IDEAFORGE"],
     "q": ["India defence indigenisation order", "India defence exports record"]},
    {"id": "rail", "name": "Railways capex",
     "thesis": "Record railway budgets fund new trains (Vande Bharat), wagons, signalling (Kavach) and dedicated freight corridors.",
     "start": 2019,
     "timeline": [["Feb 2019", "First Vande Bharat Express starts service."],
                  ["Feb 2023", "Budget raises railway capital spending to about ₹2.4 lakh crore, a record."],
                  ["2023-24", "Railway PSU stocks rally several-fold on orders and re-rating."],
                  ["2024-25", "Valuations cool; focus shifts to order execution and Kavach roll-out."]],
     "stocks": ["IRFC", "RVNL", "IRCON", "RAILTEL", "TITAGARH", "JWL", "TEXRAIL", "RITES", "IRCTC", "BEML", "HBLENGINE", "RKFORGE", "CONCOR"],
     "q": ["Indian Railways capex order", "Vande Bharat order wagon"]},
    {"id": "power", "name": "Power demand and grid (T&D)",
     "thesis": "Record electricity demand, renewables integration and data centres need new generation, transmission lines and transformers.",
     "start": 2022,
     "timeline": [["2022-23", "Peak power demand sets successive records; thermal capacity additions restart."],
                  ["2023-24", "Large transmission tenders for renewable corridors; transformer makers' order books jump."],
                  ["2024-25", "Transformer and switchgear capacity tight; T&D and power equipment stocks re-rate."]],
     "stocks": ["NTPC", "POWERGRID", "TATAPOWER", "ADANIPOWER", "JSWENERGY", "NHPC", "SJVN", "CESC", "TORNTPOWER", "KEC", "KPIL", "SIEMENS",
                "ABB", "POWERINDIA", "CGPOWER", "TARIL", "GVT&D", "VOLTAMP", "SCHNEIDER", "APARINDS", "POLYCAB", "KEI", "BHEL"],
     "q": ["India peak power demand transmission", "transformer order India grid"]},
    {"id": "solar", "name": "Renewables and solar manufacturing",
     "thesis": "PLI for solar modules, import duties and the 500 GW clean-energy target build a domestic solar and wind supply chain.",
     "start": 2021,
     "timeline": [["Apr 2021", "PLI scheme for high-efficiency solar modules approved (larger second tranche in 2022)."],
                  ["Feb 2024", "PM Surya Ghar rooftop solar scheme launched for 1 crore homes."],
                  ["Sep-Oct 2024", "Premier Energies and Waaree Energies list strongly."],
                  ["2025", "Cell manufacturing (ALMM for cells) becomes the next step; module prices fall."]],
     "stocks": ["WAAREEENER", "PREMIERENE", "SUZLON", "INOXWIND", "KPIGREEN", "ADANIGREEN", "BORORENEW", "WEBELSOLAR", "GENUSPOWER", "INOXGREEN", "NTPCGREEN", "ACMESOLAR"],
     "q": ["India solar module manufacturing PLI", "India renewable energy capacity record"]},
    {"id": "ev", "name": "Electric vehicles and batteries",
     "thesis": "Subsidies (FAME, PM E-DRIVE) and PLI for batteries and auto components drive EV adoption and a local battery supply chain.",
     "start": 2019,
     "timeline": [["Apr 2019", "FAME II subsidies for electric two-, three-wheelers and buses."],
                  ["May 2021", "PLI for advanced chemistry cell batteries (₹18,100 crore)."],
                  ["Aug 2024", "Ola Electric lists."],
                  ["Sep 2024", "PM E-DRIVE scheme replaces FAME."]],
     "stocks": ["TATAMOTORS", "TMPV", "M&M", "OLAELEC", "EXIDEIND", "ARE&M", "AMARAJABAT", "SONACOMS", "UNOMINDA", "TVSMOTOR", "BAJAJ-AUTO", "GREAVESCOT", "JBMA", "OLECTRA"],
     "q": ["India electric vehicle sales battery", "India EV policy subsidy"]},
    {"id": "dc", "name": "Data centres and AI infrastructure",
     "thesis": "AI and cloud demand plus data-localisation rules drive data-centre building, servers and power in India.",
     "start": 2023,
     "timeline": [["2023", "Generative AI boom; hyperscalers announce Indian data-centre investments."],
                  ["Mar 2024", "IndiaAI Mission approved (about ₹10,000 crore, including GPU capacity)."],
                  ["2024-25", "Server makers and GPU-cloud providers list or re-rate; data-centre land and power deals multiply."]],
     "stocks": ["NETWEB", "E2E", "ANANTRAJ", "TATACOMM", "RAILTEL", "TECHNOE", "BLUESTARCO", "HCLTECH"],
     "q": ["India data centre capacity investment", "India AI GPU data centre"]},
    {"id": "capmkt", "name": "Capital markets boom",
     "thesis": "Demat accounts multiplied after 2020 and SIP flows hit records, lifting exchanges, depositories, brokers and fund managers.",
     "start": 2020,
     "timeline": [["2020-21", "Demat accounts surge as first-time investors join during COVID."],
                  ["2023-24", "Monthly SIP flows set records; F&O volumes explode."],
                  ["Nov 2024", "SEBI tightens F&O rules; brokers' volumes dip, exchanges diversify."]],
     "stocks": ["BSE", "CDSL", "ANGELONE", "MCX", "CAMS", "KFINTECH", "360ONE", "NUVAMA", "MOTILALOFS", "HDFCAMC", "NAM-INDIA", "UTIAMC", "ABSLAMC"],
     "q": ["demat accounts record India", "SIP inflows record India"]},
    {"id": "psu", "name": "PSU re-rating",
     "thesis": "Cleaner balance sheets, higher dividends and government capex re-rated public-sector companies after years of low valuations.",
     "start": 2021,
     "timeline": [["2021-22", "PSU banks clean up bad loans; profits recover."],
                  ["2023-24", "PSU index nearly doubles; railway, power and defence PSUs lead."],
                  ["2024-25", "Valuations cool; dividends and capex remain the support."]],
     "stocks": ["SBIN", "BANKBARODA", "CANBK", "PNB", "UNIONBANK", "COALINDIA", "ONGC", "NHPC", "RECLTD", "PFC", "IRFC", "HAL", "BEL", "NBCC", "BHEL", "GAIL", "OIL"],
     "q": ["PSU stocks rally dividend", "public sector undertaking India stocks"]},
    {"id": "cdmo", "name": "Pharma CDMO and China+1 pharma",
     "thesis": "US moves to cut reliance on Chinese biotech suppliers send contract research and manufacturing work to Indian firms.",
     "start": 2023,
     "timeline": [["2023", "Global pharma looks to diversify away from Chinese contract manufacturers."],
                  ["2024", "US BIOSECURE Act proposed, targeting some Chinese biotech suppliers."],
                  ["2025", "Indian CDMOs report stronger enquiries; new listings in the space."]],
     "stocks": ["DIVISLAB", "SYNGENE", "LAURUSLABS", "PPLPHARMA", "NEULANDLAB", "COHANCE", "SUVENPHAR", "GLAND", "CONCORDBIO", "ANTHEM", "SAILIFE"],
     "q": ["India CDMO BIOSECURE", "Indian contract manufacturing pharma China plus one"]},
    {"id": "ship", "name": "Shipbuilding and ports",
     "thesis": "Maritime policy, a shipbuilding fund and defence orders aim to make India a top-10 shipbuilder; port volumes keep rising.",
     "start": 2021,
     "timeline": [["2021", "Maritime India Vision 2030 sets targets for ports and shipbuilding."],
                  ["2023-24", "Shipyard order books swell on naval and commercial orders; stocks multiply."],
                  ["2025", "Budget announces a Maritime Development Fund and shipbuilding support."]],
     "stocks": ["MAZDOCK", "COCHINSHIP", "GRSE", "ADANIPORTS", "JSWINFRA", "SCI", "SWANENERGY"],
     "q": ["India shipbuilding order shipyard", "India ports cargo record"]},
    {"id": "travel", "name": "Travel, hotels and aviation",
     "thesis": "Post-COVID travel demand met limited new hotel supply, lifting room rates; air traffic sets records.",
     "start": 2022,
     "timeline": [["2022", "Travel restrictions end; 'revenge travel' lifts occupancy and room rates."],
                  ["2023-24", "Hotel room rates exceed pre-COVID levels; domestic air traffic records."],
                  ["2025", "New hotel supply and airport expansion; growth normalises."]],
     "stocks": ["INDHOTEL", "LEMONTREE", "CHALET", "EIHOTEL", "IRCTC", "INDIGO", "EASEMYTRIP", "THOMASCOOK", "SAMHI", "JUNIPER", "VENTIVE"],
     "q": ["India hotel room rates occupancy", "India air passenger traffic record"]},
    {"id": "realty", "name": "Housing and real estate upcycle",
     "thesis": "After a decade-long slump, housing sales recovered from 2021 with low inventory, consolidation and RERA discipline.",
     "start": 2021,
     "timeline": [["2021", "Housing sales recover after COVID with low rates and stamp-duty cuts."],
                  ["2022-24", "Sales reach decade highs; listed developers gain share."],
                  ["2025", "Sales growth slows in some cities; launches stay strong."]],
     "stocks": ["DLF", "GODREJPROP", "OBEROIRLTY", "PRESTIGE", "LODHA", "PHOENIXLTD", "BRIGADE", "SOBHA", "SUNTECK", "KOLTEPATIL", "MAHLIFE", "SIGNATURE"],
     "q": ["India housing sales record developers", "India real estate launches sales"]},
    {"id": "manuf", "name": "Capital goods and manufacturing capex",
     "thesis": "Government infrastructure spending, PLI schemes and private capex revive order books for engineering and capital goods makers.",
     "start": 2021,
     "timeline": [["2020-21", "PLI schemes across 14 sectors launched to boost manufacturing."],
                  ["2022-24", "Government capex rises every budget; private capex starts to follow."],
                  ["2024-25", "Order books at record highs for many capital goods companies."]],
     "stocks": ["LT", "SIEMENS", "ABB", "CUMMINSIND", "THERMAX", "BHEL", "KIRLOSENG", "AIAENG", "GRINDWELL", "TIMKEN", "SKFINDIA", "ELGIEQUIP", "TRITURBINE", "PRAJIND", "ISGEC", "KSB"],
     "q": ["India capex order book capital goods", "India PLI manufacturing investment"]},
]

# ---------------- screener metadata ----------------
META = [
    ("th_lead", "Stock belongs to a theme that is Leading", "s"),
    ("th_imp", "Stock belongs to a theme that is Improving", "s"),
]
